# ?? SERVIDOR ??????????????????????????????????????????????????
server.port=8080

# ?? BANCO DE DADOS (PostgreSQL) ????????????????????????????????
spring.datasource.url=jdbc:postgresql://localhost:5432/evenplan_db
spring.datasource.username=postgres
spring.datasource.password=poo-666
spring.datasource.driver-class-name=org.postgresql.Driver

# ?? JPA / HIBERNATE ???????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ?? THYMELEAF ?????????????????????????????????????????????????
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html